### PR TITLE
Add Jeremy public keys

### PR DESCRIPTION
**Pull request by clodeindustrie**

### CODE REVIEW

**Review by haydngreatnews — DISMISSED** [review]

**Comment by JohannDickson** [comment]
Commits need to be signed and verified, have you added this gpg key to your github profile?

**Comment by clodeindustrie** [comment]
I think it should be good now, I have verified this other email address.

**Comment by clodeindustrie** [comment]
now it should be fine

**Review by JohannDickson — APPROVED** [review]

**Review by phil-hodgson-1st — APPROVED** [review]
Lets get this merged!

**Pull request merged**
