### PR TITLE
Update melissa_gpg_keys

### PR DESCRIPTION
**Pull request by MissaDavid**

### CODE REVIEW

**Review by mattbilson — DISMISSED** [review]

**Review by haydnnewport — DISMISSED** [review]

**Review by haydnnewport — COMMENTED** [review]
Hey Melissa - this looks pretty reasonable in terms of a change, but I'm not sure whether the backup scripts can use an ed25519 key for file encryption -- taking a stab at it on my machine, at the very least, it doesn't seem to work.

Here's the example I tried:
`gpg --encrypt-to=415FE6E2B180ACA8 --encrypt <some-file>`
where 415FE6E2B180ACA8 is your key ID in this case

**Comment by MissaDavid** [comment]
@haydnnewport Ah thanks, good to know ! I was following Emilia's PR docs but they haven't been updated for a few months, I should have known better ! I'll use another encryption and will update that :point_up_2:

**Comment by ekini** [comment]
We have moved to GPG2 so it does support ECC and these types of keys.
However, there is an issue with the key itself.

```
$gpg -k
pub   ed25519 2021-05-17 [SC] [expires: 2021-11-13]
      ABFC6F3252C8D02C85FAD48F415FE6E2B180ACA8
uid           [ unknown] Melissa David (backups) <melissa.david@springload.co.nz>
```
It does not have `E` in usage. See `[SC]` - that means, sign and certify.
`E` stands for "encrypt" and that's the reason why it's unusable for encryption:
```
gpg -e -r Melissa test.txt
gpg: Melissa: skipped: Unusable public key
gpg: test.txt: encryption failed: Unusable public key
```

**Comment by MissaDavid** [comment]
@ekini Yes you're right, I had used `ECC (sign only)` I think, so I'm rebuilding a new one so I can do both encrypt and decrypt (not that I encrypt a lot of files but you never know). Thanks both for your help :heart_eyes_cat:

**Review by ekini — APPROVED** [review]
works for me

**Review by haydnnewport — APPROVED** [review]
Ah right - I bumped up against the right problem, but had the wrong reason - thanks for that Eugene

**Pull request merged**
