### PR TITLE
Move kmayo gpg key to correct location

### PR DESCRIPTION
**Pull request by textagroup**
kmayo gpg key was in root location moved to gpg folder

### CODE REVIEW

**Review by ekini — APPROVED** [review]

**Review by JohannDickson — APPROVED** [review]

**Comment by gdelavil** [comment]
@textagroup it seems your commit is not signed. Could you please correct that? It should merge automatically after that.

**Comment by textagroup** [comment]
@gdelavil Have signed the commit and re-requested the review

**Review by gdelavil — APPROVED** [review]

**Review by haydngreatnews — APPROVED** [review]

**Comment by gdelavil** [comment]
@textagroup unfortunately your commit doesn't appear to be quite signed yet :( .  Please try again and ensure you have the little `Verified` pill: 
Screenshot 2023-04-24 at 8 59 00 AM

**Review by JohannDickson — APPROVED** [review]

**Comment by textagroup** [comment]
@gdelavil Should be properly signed now

verified

**Review by ekini — APPROVED** [review]

**Review by JohannDickson — APPROVED** [review]

**Pull request merged**
